### ISSUE TITLE
你好，反馈问题

### ISSUE THREAD

**Issue by ExpLangcn** [smallcham/sec-admin-web#3]
你好，我测试了一下，在ftp开启了弱口令，然后使用这款工具扫描出来的结果是mysql存在弱口令，但是ftp并没有，我也在字典内添加了对应的账号密码。

**Comment by smallcham** [comment]
> 你好，我测试了一下，在ftp开启了弱口令，然后使用这款工具扫描出来的结果是mysql存在弱口令，但是ftp并没有，我也在字典内添加了对应的账号密码。

扫描FTP要选择对应的FTP扫描插件，任务列表里可以看到执行的插件是什么名字，插件内容可以在插件列表中修改。

**Comment by ExpLangcn** [comment]
> > 你好，我测试了一下，在ftp开启了弱密码，然后使用这款工具扫描出来的结果是mysql存在弱密码，但是ftp并没有，我也在字典内添加了对应的账号密码。
> 
> 扫描FTP要选择对应的FTP扫描插件，任务列表里可以看到执行的插件是什么名字，插件内容可以在插件列表中修改。

你好，我选择是FTP扫描脚本

**Comment by smallcham** [comment]
> > > 你好，我测试了一下，在ftp开启了弱密码，然后使用这款工具扫描出来的结果是mysql存在弱密码，但是ftp并没有，我也在字典内添加了对应的账号密码。
> > 
> > 
> > 扫描FTP要选择对应的FTP扫描插件，任务列表里可以看到执行的插件是什么名字，插件内容可以在插件列表中修改。
> 
> 你好，我选择是FTP扫描脚本
可以确认一下ftp的端口是否对外开放了，可以在部署服务的机器上测试一下FTP能否登录，没有开的话就扫不到了，方便的话截个图看看任务列表的显示内容。

**Comment by ExpLangcn** [comment]
> > > > 你好，我测试了一下，在ftp开启了弱密码，然后使用这款工具扫描出来的结果是mysql存在弱密码，但是ftp并没有，我也在字典内添加了对应的账号密码。
> > > 
> > > 
> > > 扫描FTP要选择对应的FTP扫描插件，任务列表里可以看到执行的插件是什么名字，插件内容可以在插件列表中修改。
> > 
> > 
> > 你好，我选择是FTP扫描脚本
> > 可以确认一下ftp的端口是否对外开放了，可以在部署服务的机器上测试一下FTP能否登录，没有开的话就扫不到了，方便的话截个图看看任务列表的显示内容。

使用ftp:// 是可以连接并且登录成功的，是否可以留下VX或者QQ方便联系交流。

**Comment by smallcham** [comment]
> > > > > 你好，我测试了一下，在ftp开启了弱密码，然后使用这款工具扫描出来的结果是mysql存在弱密码，但是ftp并没有，我也在字典内添加了对应的账号密码。
> > > > 
> > > > 
> > > > 扫描FTP要选择对应的FTP扫描插件，任务列表里可以看到执行的插件是什么名字，插件内容可以在插件列表中修改。
> > > 
> > > 
> > > 你好，我选择是FTP扫描脚本
> > > 可以确认一下ftp的端口是否对外开放了，可以在部署服务的机器上测试一下FTP能否登录，没有开的话就扫不到了，方便的话截个图看看任务列表的显示内容。
> 
> 使用ftp:// 是可以连接并且登录成功的，是否可以留下VX或者QQ方便联系交流。

你微信号多少， 我加一下你

**Comment by ExpLang-CN** [comment]
> > > > > > 你好，我测试了一下，在ftp开启了弱密码，然后使用这款工具扫描出来的结果是mysql存在弱密码，但是ftp并没有，我也在字典内添加了对应的账号密码。
> > > > > 
> > > > > 
> > > > > 扫描FTP要选择对应的FTP扫描插件，任务列表里可以看到执行的插件是什么名字，插件内容可以在插件列表中修改。
> > > > 
> > > > 
> > > > 你好，我选择是FTP扫描脚本
> > > > 可以确认一下ftp的端口是否对外开放了，可以在部署服务的机器上测试一下FTP能否登录，没有开的话就扫不到了，方便的话截个图看看任务列表的显示内容。
> > 
> > 
> > 使用ftp:// 是可以连接并且登录成功的，是否可以留下VX或者QQ方便联系交流。
> 
> 你微信号多少， 我加一下你

backxyh 谢谢！
